language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
  
before_install:
  pear install pear/PHP_CodeSniffer
  - cd $TRAVIS_BUILD_DIR
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install
  - node --version
  - npm --version
  - grunt --version

script: grunt
