dist: trusty
sudo: false
language: php
matrix:
  include:
    - php: 5.2
      dist: precise
    - php: 5.3
      dist: precise
php:
  - '5.6'
  - '7'

before_install:
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - cd $TRAVIS_BUILD_DIR
  - npm install grunt
  - npm install -g grunt-cli
  - npm install
  - node --version
  - npm --version
  - grunt --version
  - git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git ./wpcs
  - phpcs --config-set installed_paths "$TRAVIS_BUILD_DIR/wpcs"

script: grunt
