language: php
php:
  - '5.2'
  - '5.6'
  - '7.0'

before_install:
  pear install pear/PHP_CodeSniffer
  - cd $TRAVIS_BUILD_DIR
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install grunt
  - npm install
  - node --version
  - npm --version
  - grunt --version

script: grunt
